apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  labels:
    app: nginx-sts
spec:
  serviceName: show-sts
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sts
  template:
    metadata:
      labels:
        app: nginx-sts
        component: show-stat-sts
    spec:
      initContainers:
      - name: download-init
        image: appropriate/curl
        imagePullPolicy: Always
        command: ["curl", "$(URL)", "-o", "$(LOCAL)", "-v"]
        env:
        - name: URL
          value: "https://raw.githubusercontent.com/kaarolch/kubernetes-examples/master/templates/error-pages/index.html"
        - name: LOCAL
          value: "/error-pages/index.html"
        volumeMounts:
          - mountPath: "/error-pages"
            name: src
      - name: tpl-init
        image: kaarol/tpl:latest
        imagePullPolicy: Always
        env:
        - name: SRC_PATH
          value: "/error-pages/"
        - name: DST_PATH
          value: "/nginx/error-pages"
        volumeMounts:
          - mountPath: "/error-pages"
            name: src
          - mountPath: "/nginx/error-pages"
            name: dst
      - name: coffe-brake
        image: busybox
        imagePullPolicy: Always
        command: ["sleep", "10s"]
      containers:
      - name: nginx-main
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: dst
      - name: update-sidecar
        image: busybox
        command: [ "/bin/sh", "-c"]
        args:
        - while true; do
            echo -en "<h2>--- $(date) ---</h2>" > /usr/share/nginx/html/stats.html;
            uptime >>  /usr/share/nginx/html/stats.html;
            sleep 5;
          done;
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: dst
  volumeClaimTemplates:
    - metadata:
        name: src
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: dst
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
---
kind: Service
apiVersion: v1
metadata:
  name: show-sts
spec:
  selector:
    component: show-stat-sts
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
