---
apiVersion: v1
kind: Pod
metadata:
  name: tools
spec:
  containers:
  - name: ubuntu-tools
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
